language: node_js
node_js:
  - "12"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm ci
  - npm run lint
  - npm run test
  - npm run-script build:prod
