language: node_js
node_js:
  - "10"
dist: bionic
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run-script build --prod
  - mv dist/index.html dist/developerli/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/developerli
  on:
    branch: master
