language: node_js
node_js:
  - "12"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run lint
  - npm run test
  - npm run-script build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/developerli
  fqdn: developer.li
  on:
    branch: master
