name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      env:
        CI: true
    - name: Install Packages
      run: npm ci
    - name: Build prod
      run: npm run build:prod --if-present
      
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: dist/developerli
        fqdn: developer.li
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
